-- MySQL Script generated by MySQL Workbench
-- 08/12/24 18:36:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blueroyals
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blueroyals` ;

-- -----------------------------------------------------
-- Schema blueroyals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blueroyals` DEFAULT CHARACTER SET latin1 ;
USE `blueroyals` ;

-- -----------------------------------------------------
-- Table `blueroyals`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blueroyals`.`user` ;

CREATE TABLE IF NOT EXISTS `blueroyals`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blueroyals`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blueroyals`.`event` ;

CREATE TABLE IF NOT EXISTS `blueroyals`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL DEFAULT NULL,
  `max_user` INT(11) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  `create_user` INT(11) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `event_date` DATETIME NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_name_UNIQUE` (`event_name` ASC),
  INDEX `fk_user_idx` (`create_user` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`create_user`)
    REFERENCES `blueroyals`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blueroyals`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blueroyals`.`subscription` ;

CREATE TABLE IF NOT EXISTS `blueroyals`.`subscription` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_event` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `is_delete` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_fk_idx` (`id_event` ASC),
  INDEX `user_fk_idx` (`id_user` ASC),
  CONSTRAINT `event_fk`
    FOREIGN KEY (`id_event`)
    REFERENCES `blueroyals`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `blueroyals`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
